language: python

dist: xenial
python:
  - 3.6

matrix:
  include:
    # OSX
    - name: "Python 3.6 on macOS"
      os: osx
      language: shell
      install: pip install -r requirements.txt
      script: pytest

# install dependencies
install: pip install -r requirments.txt

# run test
script: pytest

