language: python

python:
  - 3.6

matrix:
  include:
    # Linux
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6
    # OSX
    - name: "Python 3.6 on macOS"
      os: osx
      language: shell

# install dependencies
install: pip3 install -r requirments.txt

# run test
script: pytest

